# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    name: Say hi
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo Hi from our first workflow!
        
      - name: Show ASCII greeting
        uses: mscoutermarsh/ascii-art-action@master
        with:
          text: 'HELLO!'
  get-posts-job:
    name: GET TDS posts
    runs-on: ubuntu-latest
    
    steps:
      - name: Check-out the repo under $GITHUB_WORKSPACE
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install Scrapy
        run: pip install scrapy
      
      - name: Get TDS posts about GitHub Actions
        run: scrapy runspider posts_spider.py -o posts.json
      - name: Upload artifact                      
        uses: actions/upload-artifact@v2                        
        with:                                 
          name: posts                                 
          path: posts.json
