# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    name: Say hi
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo Hi from our first workflow!
